apiVersion: apps/v1
kind: Deployment
metadata:
  name: openai-deployment
  labels:
    app: openai
spec:
  selector:
    matchLabels:
      app: openai
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-sdk: "true"
      labels:
        app: openai
    spec:
      containers:
        - name: openai-container
          image: minkwang/mobilex-exp-backend:v0.3
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-api-key-secret
                  key: OPENAI_API_KEY
          resources:
            limits:
              cpu: "4"
              memory: "12Gi"
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: openai-service
  labels:
    app: openai
spec:
  type: ClusterIP
  selector:
    app: openai
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
